"""
SHARINGAN Complex Video Stress Test Suite

Tests 4 categories of complex videos:
1. Texture & State Change (Chocolate Sculpture)
2. Object Density & Text (PC Building)
3. State Transformation (Chemistry)
4. Action Segmentation (Woodworking)

Each test saves results to a separate folder with detailed analysis.
"""

import os
import sys
from pathlib import Path
from datetime import datetime
import tempfile
import time

# Add sharingan to path
sys.path.insert(0, str(Path(__file__).parent))

from sharingan.processor import VideoProcessor


def download_youtube_video(url: str) -> str:
    """Download YouTube video and return local path."""
    try:
        import yt_dlp
    except ImportError:
        print("ERROR: yt-dlp not installed. Install with: pip install yt-dlp")
        sys.exit(1)
    
    # Create cache directory
    cache_dir = Path(tempfile.gettempdir()) / "sharingan_youtube_cache"
    cache_dir.mkdir(exist_ok=True)
    
    # Configure yt-dlp
    ydl_opts = {
        'format': 'best[ext=mp4]',
        'outtmpl': str(cache_dir / '%(title)s-%(id)s.%(ext)s'),
        'quiet': False,
        'no_warnings': False,
    }
    
    print(f"Downloading video from: {url}")
    
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        # Extract info first to check if already downloaded
        info = ydl.extract_info(url, download=False)
        video_id = info['id']
        video_title = info['title']
        
        # Check if video already exists
        expected_path = cache_dir / f"{video_title}-{video_id}.mp4"
        if expected_path.exists():
            print(f"✓ Using cached video: {expected_path}")
            return str(expected_path)
        
        # Download video
        ydl.download([url])
        
        # Find the downloaded file
        for file in cache_dir.glob(f"*{video_id}*.mp4"):
            print(f"✓ Video downloaded: {file}")
            return str(file)
    
    raise FileNotFoundError(f"Failed to download video from {url}")


def format_timestamp(seconds: float) -> str:
    """Format seconds as MM:SS."""
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes:02d}:{secs:02d}"


def save_results(test_name: str, video_url: str, video_path: str, results: dict, queries: list, output_dir: Path):
    """Save test results to markdown file."""
    output_file = output_dir / f"{test_name}_results.md"
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(f"# SHARINGAN Stress Test: {test_name}\n\n")
        f.write(f"**Test Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write(f"**YouTube URL:** {video_url}\n\n")
        f.write("---\n\n")
        
        # Video info
        f.write("## Video Information\n\n")
        video_info = results['video_info']
        f.write(f"- **Duration:** {video_info['duration']:.1f}s ({video_info['duration']/60:.1f} min)\n")
        f.write(f"- **Total Frames:** {video_info['total_frames']:,}\n")
        f.write(f"- **Processed Frames:** {video_info['processed_frames']:,}\n")
        f.write(f"- **Original FPS:** {video_info['fps']:.1f}\n")
        f.write(f"- **Events Detected:** {len(results['events'])}\n")
        f.write(f"- **Effective Processing FPS:** {video_info['processed_frames']/video_info['duration']:.2f}\n\n")
        
        # Events
        f.write("## Detected Events\n\n")
        f.write(f"Total events detected: {len(results['events'])}\n\n")
        f.write("| # | Timestamp | Description |\n")
        f.write("|---|-----------|-------------|\n")
        for i, event in enumerate(results['events'], 1):
            timestamp_str = format_timestamp(event['timestamp'])
            f.write(f"| {i} | {timestamp_str} | {event['description']} |\n")
        f.write("\n---\n\n")
        
        # Query results
        f.write("## Query Test Results\n\n")
        for i, (query, category, answer) in enumerate(queries, 1):
            f.write(f"### Query {i}: {query}\n\n")
            f.write(f"**Category:** {category}\n\n")
            f.write(f"**Answer:** {answer}\n\n")
            f.write("---\n\n")
        
        # Summary
        f.write("## Test Summary\n\n")
        f.write(f"- **Video Duration:** {video_info['duration']:.1f}s ({video_info['duration']/60:.1f} min)\n")
        f.write(f"- **Events Detected:** {len(results['events'])}\n")
        f.write(f"- **Queries Tested:** {len(queries)}\n")
        f.write(f"- **Test Status:** ✅ Success\n\n")
        
        f.write("---\n\n")
        f.write(f"*Generated by SHARINGAN Complex Video Stress Test - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
    
    print(f"\n✓ Results saved to: {output_file}")


def test_chocolate_sculpture():
    """Test 1: Texture & State Change (Chocolate Sculpture)"""
    print("\n" + "="*80)
    print("TEST 1: TEXTURE & STATE CHANGE (Chocolate Sculpture)")
    print("="*80)
    
    test_name = "01_chocolate_sculpture"
    # Alternative video if original is unavailable
    # Original: https://www.youtube.com/watch?v=f2vO_G_pY_E (may be unavailable)
    # Alternative: Chocolate tempering tutorial
    video_url = "https://www.youtube.com/watch?v=qhZtJTUvGAU"  # Chocolate tempering basics
    
    # Create output directory
    output_dir = Path("stress_test_results") / test_name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("\nStep 1: Downloading video...")
    print("-" * 80)
    video_path = download_youtube_video(video_url)
    
    print("\nStep 2: Initializing processor (HIGH QUALITY preset)...")
    print("-" * 80)
    processor = VideoProcessor(
        vlm_model='clip',
        device='auto',
        target_fps=8.0,  # High quality for texture details
        enable_temporal=True,
        batch_size=32
    )
    
    print("\nStep 3: Processing video...")
    print("-" * 80)
    start_time = time.time()
    results = processor.process(video_path)
    processing_time = time.time() - start_time
    print(f"\n✓ Processing completed in {processing_time:.1f}s ({processing_time/60:.1f} min)")
    
    print("\nStep 4: Testing queries...")
    print("-" * 80)
    
    queries = [
        # Texture & State queries
        ("What is the chocolate being used for?", "Content"),
        ("When is chocolate being melted?", "State Change"),
        ("When is chocolate being poured?", "Action"),
        ("When is chocolate being painted?", "Action"),
        ("When is chocolate being carved?", "Action"),
        ("When is chocolate being sprayed?", "Action"),
        ("What tools are being used?", "Equipment"),
        ("When is the spray gun used?", "Equipment"),
        ("When is the lathe used?", "Equipment"),
        ("What happens at the beginning?", "Timing"),
        ("What happens in the middle?", "Timing"),
        ("What happens at the end?", "Timing"),
        ("When is the dragon assembled?", "Process"),
        ("When is the final sculpture shown?", "Final Result"),
        ("Summarize the sculpture process", "Summary"),
    ]
    
    query_results = []
    for query, category in queries:
        print(f"\nQuery [{category}]: {query}")
        print("-" * 40)
        answer = processor.chat(query, use_llm=False)
        print(f"Answer: {answer}")
        query_results.append((query, category, answer))
    
    print("\nStep 5: Saving results...")
    print("-" * 80)
    save_results(test_name, video_url, video_path, results, query_results, output_dir)
    
    print(f"\n✅ Test 1 completed! Results in: {output_dir}")


def test_pc_building():
    """Test 2: Object Density & Text (PC Building)"""
    print("\n" + "="*80)
    print("TEST 2: OBJECT DENSITY & TEXT (PC Building)")
    print("="*80)
    
    test_name = "02_pc_building"
    video_url = "https://www.youtube.com/watch?v=PXaLc9AYIcg"
    
    # Create output directory
    output_dir = Path("stress_test_results") / test_name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("\nStep 1: Downloading video...")
    print("-" * 80)
    video_path = download_youtube_video(video_url)
    
    print("\nStep 2: Initializing processor (HIGH QUALITY preset for text)...")
    print("-" * 80)
    processor = VideoProcessor(
        vlm_model='clip',
        device='auto',
        target_fps=8.0,  # High quality for text detection
        enable_temporal=True,
        batch_size=32
    )
    
    print("\nStep 3: Processing video...")
    print("-" * 80)
    start_time = time.time()
    results = processor.process(video_path)
    processing_time = time.time() - start_time
    print(f"\n✓ Processing completed in {processing_time:.1f}s ({processing_time/60:.1f} min)")
    
    print("\nStep 4: Testing queries...")
    print("-" * 80)
    
    queries = [
        # Component identification
        ("What components are shown?", "Content"),
        ("When is the CPU installed?", "Action"),
        ("When is the RAM installed?", "Action"),
        ("When is the GPU installed?", "Action"),
        ("When is the motherboard shown?", "Component"),
        ("When are cables being connected?", "Action"),
        ("What brands are visible?", "Text/Brand"),
        ("When is Intel shown?", "Text/Brand"),
        ("When is NVIDIA shown?", "Text/Brand"),
        ("When is ASUS shown?", "Text/Brand"),
        ("What happens first?", "Timing"),
        ("What happens at the beginning?", "Timing"),
        ("What happens in the middle?", "Timing"),
        ("What happens at the end?", "Timing"),
        ("When is the PC powered on?", "Final Result"),
        ("Summarize the PC building process", "Summary"),
    ]
    
    query_results = []
    for query, category in queries:
        print(f"\nQuery [{category}]: {query}")
        print("-" * 40)
        answer = processor.chat(query, use_llm=False)
        print(f"Answer: {answer}")
        query_results.append((query, category, answer))
    
    print("\nStep 5: Saving results...")
    print("-" * 80)
    save_results(test_name, video_url, video_path, results, query_results, output_dir)
    
    print(f"\n✅ Test 2 completed! Results in: {output_dir}")


def test_chemistry():
    """Test 3: State Transformation (Chemistry)"""
    print("\n" + "="*80)
    print("TEST 3: STATE TRANSFORMATION (Chemistry)")
    print("="*80)
    
    test_name = "03_chemistry"
    video_url = "https://www.youtube.com/watch?v=zFZ5jQ0yuNA"
    
    # Create output directory
    output_dir = Path("stress_test_results") / test_name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("\nStep 1: Downloading video...")
    print("-" * 80)
    video_path = download_youtube_video(video_url)
    
    print("\nStep 2: Initializing processor (BALANCED preset for long video)...")
    print("-" * 80)
    processor = VideoProcessor(
        vlm_model='clip',
        device='auto',
        target_fps=5.0,  # Balanced for long video
        enable_temporal=True,
        batch_size=32
    )
    
    print("\nStep 3: Processing video...")
    print("-" * 80)
    start_time = time.time()
    results = processor.process(video_path)
    processing_time = time.time() - start_time
    print(f"\n✓ Processing completed in {processing_time:.1f}s ({processing_time/60:.1f} min)")
    
    print("\nStep 4: Testing queries...")
    print("-" * 80)
    
    queries = [
        # State transformation queries
        ("What materials are being used?", "Content"),
        ("When does the liquid turn purple?", "State Change"),
        ("When does the liquid turn clear?", "State Change"),
        ("When is heating applied?", "Action"),
        ("When is mixing done?", "Action"),
        ("When is filtering done?", "Action"),
        ("What glassware is visible?", "Equipment"),
        ("When is a beaker used?", "Equipment"),
        ("When is a flask used?", "Equipment"),
        ("When is distillation shown?", "Process"),
        ("What happens at the beginning?", "Timing"),
        ("What happens in the middle?", "Timing"),
        ("What happens at the end?", "Timing"),
        ("When is the final product shown?", "Final Result"),
        ("Summarize the chemical process", "Summary"),
    ]
    
    query_results = []
    for query, category in queries:
        print(f"\nQuery [{category}]: {query}")
        print("-" * 40)
        answer = processor.chat(query, use_llm=False)
        print(f"Answer: {answer}")
        query_results.append((query, category, answer))
    
    print("\nStep 5: Saving results...")
    print("-" * 80)
    save_results(test_name, video_url, video_path, results, query_results, output_dir)
    
    print(f"\n✅ Test 3 completed! Results in: {output_dir}")


def test_woodworking():
    """Test 4: Action Segmentation (Woodworking)"""
    print("\n" + "="*80)
    print("TEST 4: ACTION SEGMENTATION (Woodworking)")
    print("="*80)
    
    test_name = "04_woodworking"
    video_url = "https://www.youtube.com/watch?v=1iG1sXaYhwY"
    
    # Create output directory
    output_dir = Path("stress_test_results") / test_name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("\nStep 1: Downloading video...")
    print("-" * 80)
    video_path = download_youtube_video(video_url)
    
    print("\nStep 2: Initializing processor (BALANCED preset for long video)...")
    print("-" * 80)
    processor = VideoProcessor(
        vlm_model='clip',
        device='auto',
        target_fps=5.0,  # Balanced for long video
        enable_temporal=True,
        batch_size=32
    )
    
    print("\nStep 3: Processing video...")
    print("-" * 80)
    start_time = time.time()
    results = processor.process(video_path)
    processing_time = time.time() - start_time
    print(f"\n✓ Processing completed in {processing_time:.1f}s ({processing_time/60:.1f} min)")
    
    print("\nStep 4: Testing queries...")
    print("-" * 80)
    
    queries = [
        # Action segmentation queries
        ("What is being built?", "Content"),
        ("When is wood being selected?", "Phase"),
        ("When is the form being built?", "Phase"),
        ("When is epoxy being poured?", "Phase"),
        ("When is sanding shown?", "Action"),
        ("When is buffing shown?", "Action"),
        ("When is finishing applied?", "Phase"),
        ("What tools are being used?", "Equipment"),
        ("When is the router used?", "Equipment"),
        ("When is the sander used?", "Equipment"),
        ("What are the main building steps?", "Process"),
        ("What happens at the beginning?", "Timing"),
        ("What happens in the middle?", "Timing"),
        ("What happens at the end?", "Timing"),
        ("When is the final table shown?", "Final Result"),
        ("Summarize the table building process", "Summary"),
    ]
    
    query_results = []
    for query, category in queries:
        print(f"\nQuery [{category}]: {query}")
        print("-" * 40)
        answer = processor.chat(query, use_llm=False)
        print(f"Answer: {answer}")
        query_results.append((query, category, answer))
    
    print("\nStep 5: Saving results...")
    print("-" * 80)
    save_results(test_name, video_url, video_path, results, query_results, output_dir)
    
    print(f"\n✅ Test 4 completed! Results in: {output_dir}")


def main():
    """Run all stress tests."""
    print("\n" + "="*80)
    print("SHARINGAN COMPLEX VIDEO STRESS TEST SUITE")
    print("="*80)
    print("\nThis suite will test 4 categories of complex videos:")
    print("1. Texture & State Change (Chocolate Sculpture)")
    print("2. Object Density & Text (PC Building)")
    print("3. State Transformation (Chemistry)")
    print("4. Action Segmentation (Woodworking)")
    print("\nEach test will save results to: stress_test_results/<test_name>/")
    print("="*80)
    
    # Create main results directory
    results_dir = Path("stress_test_results")
    results_dir.mkdir(exist_ok=True)
    
    # Run all tests
    tests = [
        ("1", "Chocolate Sculpture", test_chocolate_sculpture),
        ("2", "PC Building", test_pc_building),
        ("3", "Chemistry", test_chemistry),
        ("4", "Woodworking", test_woodworking),
    ]
    
    print("\nWhich tests would you like to run?")
    print("1. Chocolate Sculpture (Texture & State Change)")
    print("2. PC Building (Object Density & Text)")
    print("3. Chemistry (State Transformation)")
    print("4. Woodworking (Action Segmentation)")
    print("5. Run ALL tests")
    
    choice = input("\nEnter test number (1-5) or 'all': ").strip().lower()
    
    if choice in ['5', 'all']:
        # Run all tests
        for num, name, test_func in tests:
            try:
                test_func()
            except Exception as e:
                print(f"\n❌ Test {num} ({name}) failed with error: {e}")
                import traceback
                traceback.print_exc()
                continue
    elif choice in ['1', '2', '3', '4']:
        # Run specific test
        test_num = int(choice) - 1
        num, name, test_func = tests[test_num]
        try:
            test_func()
        except Exception as e:
            print(f"\n❌ Test {num} ({name}) failed with error: {e}")
            import traceback
            traceback.print_exc()
    else:
        print("Invalid choice. Exiting.")
        return
    
    print("\n" + "="*80)
    print("STRESS TEST SUITE COMPLETED")
    print("="*80)
    print(f"\nAll results saved to: {results_dir.absolute()}")
    print("\nCheck individual test folders for detailed results:")
    for num, name, _ in tests:
        test_dir = results_dir / f"0{num}_{name.lower().replace(' ', '_')}"
        if test_dir.exists():
            print(f"  - {test_dir}")


if __name__ == "__main__":
    main()
