"""Configuration module for SHARINGAN."""

from .prompts import (
    TEMPORALBENCH_CAPTION_PROMPT,
    GENERAL_CAPTION_PROMPT,
    COOKING_CAPTION_PROMPT,
    SPORTS_CAPTION_PROMPT,
    SURVEILLANCE_CAPTION_PROMPT,
    TUTORIAL_CAPTION_PROMPT,
    TEMPORALBENCH_SYSTEM_PROMPT,
    GENERAL_SYSTEM_PROMPT,
    COOKING_SYSTEM_PROMPT,
    SPORTS_SYSTEM_PROMPT,
    SURVEILLANCE_SYSTEM_PROMPT,
    TUTORIAL_SYSTEM_PROMPT,
    PROMPT_PRESETS,
    get_preset,
    list_presets
)

__all__ = [
    'TEMPORALBENCH_CAPTION_PROMPT',
    'GENERAL_CAPTION_PROMPT',
    'COOKING_CAPTION_PROMPT',
    'SPORTS_CAPTION_PROMPT',
    'SURVEILLANCE_CAPTION_PROMPT',
    'TUTORIAL_CAPTION_PROMPT',
    'TEMPORALBENCH_SYSTEM_PROMPT',
    'GENERAL_SYSTEM_PROMPT',
    'COOKING_SYSTEM_PROMPT',
    'SPORTS_SYSTEM_PROMPT',
    'SURVEILLANCE_SYSTEM_PROMPT',
    'TUTORIAL_SYSTEM_PROMPT',
    'PROMPT_PRESETS',
    'get_preset',
    'list_presets'
]
